INSERT INTO REGISTEREDUSER(ID,DTYPE,ORGANISATION) VALUES('W','StaffUser','University of Portsmouth')
INSERT INTO REGISTEREDUSER(ID,DTYPE,ORGANISATION) VALUES('CR','StudentUser','University of Portsmouth')
INSERT INTO REGISTEREDUSER(ID,DTYPE,ORGANISATION) VALUES('Q','StaffUser','University of Portsmouth')

INSERT INTO PROJECTCATEGORY("NAME") VALUES('Postgraduate')
INSERT INTO PROJECTCATEGORY("NAME") VALUES('Undergraduate')
INSERT INTO PROJECTCATEGORY("NAME") VALUES('Engineering')
INSERT INTO PROJECTCATEGORY("NAME") VALUES('Study')

INSERT INTO PROJECTIDEA(TITLE,ACADEMICQUESTION,AIMSANDOBJECTIVES,DESCRIPTION,INTENDEDFOR,STATUS,SUBMISSIONDATE,OWNER_ID) VALUES('Sample','The Question','The Objective','The Description','Intended For','Provisional','2017-02-21','W')