/**
 * This file was generated by the JPA Modeler
 */
package Entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

/**
 * @author a
 */
@Entity
public class Person implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Long id;

    @Basic
    private String Name;

    @Basic
    private String Surname;

    @Basic
    private String Gender;

    @Basic
    private String DateOfBirth;

    @Basic
    private String Nationality;

    @Basic
    private String username;

    @Basic
    private String Password;

    @OneToOne(targetEntity = PersonStatus.class)
    private PersonStatus personStatus;

    @OneToMany(targetEntity = Mail.class)
    private List<Mail> mails;

    @OneToMany(targetEntity = TelephoneNumber.class)
    private List<TelephoneNumber> telephoneNumbers;

    @OneToMany(targetEntity = Addres.class)
    private List<Addres> addreses;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSurname() {
        return this.Surname;
    }

    public void setSurname(String Surname) {
        this.Surname = Surname;
    }

    public String getGender() {
        return this.Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public String getDateOfBirth() {
        return this.DateOfBirth;
    }

    public void setDateOfBirth(String DateOfBirth) {
        this.DateOfBirth = DateOfBirth;
    }

    public String getNationality() {
        return this.Nationality;
    }

    public void setNationality(String Nationality) {
        this.Nationality = Nationality;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public PersonStatus getPersonStatus() {
        return this.personStatus;
    }

    public void setPersonStatus(PersonStatus personStatus) {
        this.personStatus = personStatus;
    }

    public List<Mail> getMails() {
        return this.mails;
    }

    public void setMails(List<Mail> mails) {
        this.mails = mails;
    }

    public List<TelephoneNumber> getTelephoneNumbers() {
        return this.telephoneNumbers;
    }

    public void setTelephoneNumbers(List<TelephoneNumber> telephoneNumbers) {
        this.telephoneNumbers = telephoneNumbers;
    }

    public List<Addres> getAddreses() {
        return this.addreses;
    }

    public void setAddreses(List<Addres> addreses) {
        this.addreses = addreses;
    }

}
