/**
 * This file was generated by the JPA Modeler
 */
package Entities;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * @author a
 */
@Entity
public class Project implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Title;

    @Basic
    private Date ProjectStartDate;

    @Basic
    private Date ProjectEndDate;

    @OneToOne(targetEntity = Organazation.class)
    private Organazation organazation;

    @OneToMany(targetEntity = Feedback.class)
    private List<Feedback> feedbacks;

    @OneToMany(targetEntity = Milestone.class)
    private List<Milestone> milestones;

    @OneToMany(targetEntity = Mark.class)
    private List<Mark> marks;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Date getProjectStartDate() {
        return this.ProjectStartDate;
    }

    public void setProjectStartDate(Date ProjectStartDate) {
        this.ProjectStartDate = ProjectStartDate;
    }

    public Date getProjectEndDate() {
        return this.ProjectEndDate;
    }

    public void setProjectEndDate(Date ProjectEndDate) {
        this.ProjectEndDate = ProjectEndDate;
    }

    public Organazation getOrganazation() {
        return this.organazation;
    }

    public void setOrganazation(Organazation organazation) {
        this.organazation = organazation;
    }

    public List<Feedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(List<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

    public List<Milestone> getMilestones() {
        return this.milestones;
    }

    public void setMilestones(List<Milestone> milestones) {
        this.milestones = milestones;
    }

    public List<Mark> getMarks() {
        return this.marks;
    }

    public void setMarks(List<Mark> marks) {
        this.marks = marks;
    }

}
