/**
 * This file was generated by the JPA Modeler
 */
package Entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * @author a
 */
@Entity
public class Staff implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Staffnumber;

    @OneToOne(targetEntity = Person.class)
    private Person person;

    @OneToMany(targetEntity = Feedback.class)
    private List<Feedback> feedbacks;

    @OneToMany(targetEntity = Project.class)
    private List<Project> projects;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStaffnumber() {
        return this.Staffnumber;
    }

    public void setStaffnumber(String Staffnumber) {
        this.Staffnumber = Staffnumber;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public List<Feedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(List<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

    public List<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

}
